language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

before_script:
  - composer install

script:
  - vendor/bin/phpunit --verbose --coverage-text --coverage-clover=clover.xml --colors

after_script:
  - sh .travis.coverage.sh

matrix:
  allow_failures:
    - php: hhvm
